### PR TITLE
Add article on preinstalled packages

### PR DESCRIPTION
**Pull request by AdmiralAsshat**
This article adds an overview article on the applications that are preinstalled with Korora. It attempts to organize articles according to common use-cases.

**NOTE**: This article has been developed with the Cinnamon deskop in mind, although most of the apps should be common to any GNOME-based desktop. Nonetheless, I suggest that the article be reviewed to accommodate any deviations in the GNOME, Xfce, MATE, or KDE versions. I have noted the *Back in Time* app, for instance, as specific to KDE only.

### CODE REVIEW

**Comment by jimkp** [comment]
merged, thank you for the contribution

**Comment by jimkp** [comment]
I'm undecided how to deploy this. I realise it is a major exercise. Thanks for the effort. The layout is great and probably the best way to do it. I would like to see this used and promoted.

However there are some differences between desktops. Plasma is more than 50% different and there are variations on other desktops too. I'm wondering if it would be better to have an introduction on General and separate versions under each desktop after checking each one, linked from the introduction. I think trying to cover all desktops in one document would become confusing for both the writer and the reader.

There are a couple of issues but only minor. The TOC hierarchy seems inconsistent, compare the first few with the balance. There are also a couple of typos, spellchecking needed :). There is no video editor listed, I think all GTK desktops have pitivi (check needed) and Plasma uses Kdenlive.

**Comment by dyoungwd** [comment]
do we need guidance on all apps that come as default though ? If a user wants to use them, would it not be better for then to go to the app in question website and read the official docs?

**Comment by jimkp** [comment]
> do we need guidance on all apps that come as default though ? If a user wants to use them, would it not be better for then to go to the app in question website and read the official docs?

The aim is to help new users to find the right application. It has been asked about before and can be useful

**Pull request merged**
